baseURL = "https://moya4monja.github.io/"
languageCode = "ja-jp"
weight = 1
title = "moya4monja blog"
publishDir = "public"  # 公開ファイルのディレクトリ名
theme= "hugo-bootstrap-premium" # 使用するテーマ名
hasCJKLanguage = true # 記事のサマリー機能を有効にする。trueにしないと記事サマリーの文章量が大きくなりすぎる。
paginate = 10 # 一つのページに何個まで記事を載せるか。
paginatePath = "page"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	code = "/:filename/"
	
[author]
	name = "moya4monja"
	email = "moyasimonja@gmail.com"
	
[params.theme]
	name = "yeti"
  
[params]
	BrandImage = "/logo.png"
	brand = "moya4monja blog"
	topline = "moya4monjaのブログ"
	footline = "Copyright&copy; <a href='/2019/04/08/about/'>moya4monja</a>"
	showRightSidebar = true
	highlight = "default"
	twitter  = "moya4monja"
	github   = "moya4monja"

[[menu.main]]
	name = "Home"
	identifier = "home"
	url = "/"
	weight = -200
	pre = "<i class='fa fa-home'></i>"

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/post/"
	weight = -180
	pre = "<i class='fa fa-archive'></i>"

[[menu.main]]
	name = "About"
	identifier = ""
	url = "//2019/04/08/about/"
	weight = -100
	# pre = "<i class='fa fa-info-circle'></i>"